services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    env_file: 
      - .env
    expose:
      - 3306
    volumes:
      - ${DB_VOLUME_DIR}:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: on-failure
    env_file:
      - .env
    expose:
      - 9000
    volumes: 
      - ${WP_VOLUME_DIR}:/var/www/html
    depends_on: 
      - mariadb
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - ${WP_VOLUME_DIR}:/var/www/html

networks:
  default:
    driver: bridge
