services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: on-failure
    env_file: 
      - .env
    ports:
      - 3306:3306
    volumes:
      - ${DB_VOLUME_DIR}:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: on-failure
    env_file:
      - .env
    volumes: 
      - ${WP_VOLUME_DIR}:/var/www/html
    depends_on: 
      - mariadb
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - 433:433
    volumes:
      - ${WP_VOLUME_DIR}:/var/www/html
    depends_on:
      - wordpress

networks:
  default:
    driver: bridge
