services:

  mariadb:
    build: ./requirements/mariadb/
    restart: on-failure
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress/
    restart: on-failure
    env_file: .env
    volumes: 
      - wordpress_data:/var/www/html
    depends_on: 
      - mariadb
    
  nginx:
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - 433:433
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress


  volumes:

      db_data:
        driver_opts:
          type: 'none'
          device: /home/rbarbier/data/db
          o: bind

      wordpress_data:
        driver_opts:
          type: 'none'
          device: /home/rbarbier/data/wordpress
          o: bind

  networks:
    default:
      driver: bridge



       
